name: first_workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-20.04
    steps:
      - name: print hello
        run: echo "hello."
      - name: print goodbye
        run: echo "good-bye."
      
